### ISSUE TITLE
Serialization Issue 

### ISSUE THREAD

**Issue by tumberger** [Consensys/gnark#797]
Serialization fails for the latest gnark develop branch, version
```
github.com/consensys/gnark v0.8.1-0.20230728123254-716f7df700b1
github.com/consensys/gnark-crypto v0.11.1
```
with the following error:
```
 # github.com/consensys/gnark/constraint/bls24-317
 golang/pkg/mod/github.com/consensys/gnark@v0.8.1-0.20230728123254-716f7df700b1/constraint/bls24-317/gkr.go:44:38: undefined: gkr.Gates
# github.com/consensys/gnark/constraint/bw6-633
 golang/pkg/mod/github.com/consensys/gnark@v0.8.1-0.20230728123254-716f7df700b1/constraint/bw6-633/gkr.go:44:38: undefined: gkr.Gates
# github.com/consensys/gnark/constraint/bls12-377
 golang/pkg/mod/github.com/consensys/gnark@v0.8.1-0.20230728123254-716f7df700b1/constraint/bls12-377/gkr.go:44:38: undefined: gkr.Gates
# github.com/consensys/gnark/constraint/bw6-761
 golang/pkg/mod/github.com/consensys/gnark@v0.8.1-0.20230728123254-716f7df700b1/constraint/bw6-761/gkr.go:44:38: undefined: gkr.Gates
# github.com/consensys/gnark/constraint/bls12-381
 golang/pkg/mod/github.com/consensys/gnark@v0.8.1-0.20230728123254-716f7df700b1/constraint/bls12-381/gkr.go:44:38: undefined: gkr.Gates
# github.com/consensys/gnark/constraint/bls24-315
 golang/pkg/mod/github.com/consensys/gnark@v0.8.1-0.20230728123254-716f7df700b1/constraint/bls24-315/gkr.go:44:38: undefined: gkr.Gates
# github.com/consensys/gnark/constraint/bn254
 golang/pkg/mod/github.com/consensys/gnark@v0.8.1-0.20230728123254-716f7df700b1/constraint/bn254/gkr.go:44:38: undefined: gkr.Gates
```

For a previous gnark version, e.g. `v0.7.2-0.20230605143745-6ec0af711b06`, this error doesn't occur.

Short sample code to reproduce for Plonk:

```
package main

import (
	"bytes"
	"log"
	"os"

	"github.com/consensys/gnark-crypto/ecc"
	"github.com/consensys/gnark/backend/plonk"
	"github.com/consensys/gnark/frontend"
	"github.com/consensys/gnark/frontend/cs/scs"

	"github.com/consensys/gnark/examples/cubic"
)

func main() {
	var circuit cubic.Circuit

	//////////// COMPILE ////////////
	ccs, err := frontend.Compile(ecc.BN254.ScalarField(), scs.NewBuilder, &circuit)

	// SERIALIZE - WRITE THE CCS
	var buf bytes.Buffer
	_, _ = ccs.WriteTo(&buf)

	err = os.WriteFile("ccs.dat", buf.Bytes(), 0644)
	if err != nil {
		log.Fatal(err)
	}

	//////////// SETUP ////////////
	// DESERIALIZE - READ THE CCS
	_ccs, err := os.ReadFile("ccs.dat")
	if err != nil {
		log.Fatal(err)
	}
	_buf := *bytes.NewBuffer(_ccs)
	newCCS := plonk.NewCS(ecc.BN254)
	_, _ = newCCS.ReadFrom(&_buf)

}
```

**Comment by tumberger** [comment]
On a related note, I just tried doing the full serialization / deserialization for Plonk in version
```
github.com/consensys/gnark v0.7.2-0.20230605143745-6ec0af711b06
github.com/consensys/gnark-crypto v0.11.1
```
which fails with the following error:

```
panic: Failed to read prover key: invalid fr.Element encoding
goroutine 1 [running]:
main.main()
/serialize.go:130 +0x72b
exit status 2
```

For Groth16, reading the prover / verifier key works fine.

The following is the code to replicate:

```
package main

import (
	"bytes"
	"log"
	"os"

	"github.com/consensys/gnark-crypto/ecc"
	"github.com/consensys/gnark/backend/plonk"
	"github.com/consensys/gnark/backend/witness"
	"github.com/consensys/gnark/frontend"
	"github.com/consensys/gnark/frontend/cs/scs"
	"github.com/consensys/gnark/test"

	"github.com/consensys/gnark/examples/cubic"
)

func main() {
	var circuit cubic.Circuit

	//////////// COMPILE ////////////
	ccs, err := frontend.Compile(ecc.BN254.ScalarField(), scs.NewBuilder, &circuit)

	// SERIALIZE - WRITE THE CCS
	var buf bytes.Buffer
	_, _ = ccs.WriteTo(&buf)

	err = os.WriteFile("ccs.dat", buf.Bytes(), 0644)
	if err != nil {
		log.Fatal(err)
	}

	//////////// SETUP ////////////
	// DESERIALIZE - READ THE CCS
	_ccs, err := os.ReadFile("ccs.dat")
	if err != nil {
		log.Fatal(err)
	}
	_buf := *bytes.NewBuffer(_ccs)
	newCCS := plonk.NewCS(ecc.BN254)
	_, _ = newCCS.ReadFrom(&_buf)

	// CREATE SRS
	srs, err := test.NewKZGSRS(ccs)
	if err != nil {
		panic("Failed to create srs: " + err.Error())
	}

	// CREATE PK, VK
	pk, vk, err := plonk.Setup(ccs, srs)
	if err != nil {
		panic("Setup failed!")
	}

	// SERIALIZE - WRITE THE PK & VK
	_, _ = pk.WriteTo(&buf)
	err = os.WriteFile("pk.dat", buf.Bytes(), 0644)
	if err != nil {
		log.Fatal(err)
	}
	_, _ = vk.WriteTo(&buf)
	err = os.WriteFile("vk.dat", buf.Bytes(), 0644)
	if err != nil {
		log.Fatal(err)
	}

	//////////// WITNESS ////////////
	w := cubic.Circuit{}
	w.X = 3
	w.Y = 35
	wit, err := frontend.NewWitness(&w, ecc.BN254.ScalarField())

	// Binary marshalling
	data, err := wit.MarshalBinary()
	if err != nil {
		panic("Failed to marshal binary: " + err.Error())
	}

	// SERIALIZE write binary marshalled data to file
	err = os.WriteFile("witness.dat", data, 0644)
	if err != nil {
		panic("Failed to write to file: " + err.Error())
	}

	//////////// PROVE ////////////
	// DESESERIALIZE
	_wit, err := os.ReadFile("witness.dat")
	if err != nil {
		panic("Failed to read from file: " + err.Error())
	}
	_pk, err := os.ReadFile("pk.dat")
	if err != nil {
		panic("Failed to read from file: " + err.Error())
	}
	_vk, err := os.ReadFile("vk.dat")
	if err != nil {
		panic("Failed to read from file: " + err.Error())
	}

	// Reconstruct witness
	newWitness, _ := witness.New(ecc.BN254.ScalarField())
	if err != nil {
		panic("Failed to create new witness: " + err.Error())
	}
	newPK := plonk.NewProvingKey(ecc.BN254)
	newVK := plonk.NewVerifyingKey(ecc.BN254)

	// Unmarshal Witness
	err = newWitness.UnmarshalBinary(_wit)
	if err != nil {
		panic("Failed to unmarshal binary: " + err.Error())
	}

	// Read PK
	_buf = *bytes.NewBuffer(_pk)
	_, err = newPK.ReadFrom(&_buf)
	if err != nil {
		panic("Failed to read prover key: " + err.Error())
	}

	// Read VK
	_buf = *bytes.NewBuffer(_vk)
	_, err = newVK.ReadFrom(&_buf)
	if err != nil {
		panic("Failed to read verifier key: " + err.Error())
	}

	_, err = plonk.Prove(newCCS, newPK, newWitness)
}
```
