### ISSUE TITLE
How to represent a 2D array of frontend.Variables?

### ISSUE THREAD

**Issue by drakstik** [Consensys/gnark#798]
Hi, I am trying to work with 2D arrays, but I get this error:
```
16:26:11 INF compiling circuit
16:26:11 INF parsed circuit inputs nbPublic=9 nbSecret=9
16:26:11 INF building constraint builder nbConstraints=1
16:26:11 WRN circuit has unconstrained inputs
panic: unrecognized R1CS curve type

goroutine 1 [running]:
github.com/consensys/gnark/backend/groth16.Setup({0x0?, 0x0?})
        /home/x/go/pkg/mod/github.com/consensys/gnark@v0.8.0/backend/groth16/groth16.go:286 +0x4a5
main.main()
        /home/x/PhotoProof/src/main.go:289 +0x7c
exit status 2
```

This is the simple main.go code I'm running:
```
func main() {
	// compiles our circuit into a R1CS
	var circuit Matrix
	ccs, _ := frontend.Compile(ecc.BN254.ScalarField(), r1cs.NewBuilder, &circuit)

	// groth16 zkSNARK: Setup
	pk, vk, _ := groth16.Setup(ccs)

	// witness definition

	a := [3][3]frontend.Variable{{1, 2, 3}, {4, 5, 6}, {7, 8, 9}}

	b := [3][3]frontend.Variable{{1, 2, 3}, {4, 5, 6}, {7, 8, 9}}

	assignment := Matrix{X: a, Y: b} // X is secret, Y is public.
	witness, _ := frontend.NewWitness(&assignment, ecc.BN254.ScalarField())
	publicWitness, _ := witness.Public()

	// groth16: Prove & Verify
	proof, _ := groth16.Prove(ccs, pk, witness) // This proof can be sent alongside verification and public witness Y (i.e. the output).
	groth16.Verify(proof, vk, publicWitness)
}

// A Matrix consists of two fields N=16
type Matrix struct {
	X [3][3]frontend.Variable `gnark:"X, secret"` // X = [N*N]frontend.Variable
	Y [3][3]frontend.Variable `gnark:",public"`
}

func (circuit *Matrix) Define(api frontend.API) error {
	api.AssertIsEqual(circuit.Y[0][2], circuit.X[0][2])
	return nil
}
```

It fails at the "pk, vk, _ := groth16.Setup(ccs)" line in the main function.

I do not know if this is the same issue as [#236](https://github.com/Consensys/gnark/issues/236) but please help!

**Comment by gbotrel** [comment]
hi -- can you reproduce on `develop`; (I can't). v0.9.0 (merge develop into master) is coming and may fix your issue.

**Comment by drakstik** [comment]
> hi -- can you reproduce on `develop`; (I can't). v0.9.0 (merge develop into master) is coming and may fix your issue.

I have just tested it on v0.9.0 and it still has the same results. Also, by `develop` do you mean this branch????: https://github.com/Consensys/gnark/tree/thedarkjester-develop

**Comment by ivokub** [comment]
Yes, it is allowed. I think you have some dependency mismatch or maybe you are not running the code in the example?

I did
```bash
mkdir matrix
cd matrix
go mod init matrix
go get github.com/consensys/gnark
# create main.go as below
go mod tidy
go run main.go
```

file `main.go`
```go
package main

import (
        "github.com/consensys/gnark-crypto/ecc"
        "github.com/consensys/gnark/backend/groth16"
        "github.com/consensys/gnark/frontend"
        "github.com/consensys/gnark/frontend/cs/r1cs"
)

func main() {
        // compiles our circuit into a R1CS
        var circuit Matrix
        ccs, _ := frontend.Compile(ecc.BN254.ScalarField(), r1cs.NewBuilder, &circuit)

        // groth16 zkSNARK: Setup
        pk, vk, _ := groth16.Setup(ccs)

        // witness definition

        a := [3][3]frontend.Variable{{1, 2, 3}, {4, 5, 6}, {7, 8, 9}}

        b := [3][3]frontend.Variable{{1, 2, 3}, {4, 5, 6}, {7, 8, 9}}

        assignment := Matrix{X: a, Y: b} // X is secret, Y is public.
        witness, _ := frontend.NewWitness(&assignment, ecc.BN254.ScalarField())
        publicWitness, _ := witness.Public()

        // groth16: Prove & Verify
        proof, _ := groth16.Prove(ccs, pk, witness) // This proof can be sent alongside verification and public witness Y (i.e. the output).
        groth16.Verify(proof, vk, publicWitness)
}

// A Matrix consists of two fields N=16
type Matrix struct {
        X [3][3]frontend.Variable `gnark:"X, secret"` // X = [N*N]frontend.Variable
        Y [3][3]frontend.Variable `gnark:",public"`
}

func (circuit *Matrix) Define(api frontend.API) error {
        api.AssertIsEqual(circuit.Y[0][2], circuit.X[0][2])
        return nil
}
```

**Comment by drakstik** [comment]
Awesome, it worked. I did have dependency issues! Thanks for the fast response.
